version: "3.9"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
    ports:
      - '5432:5432'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  web:
    build: .
    working_dir: /usr/src/app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default_database
      - POSTGRES_HOST=db
    depends_on:
      - db
